M48
; DRILL file {KiCad 7.0.6-7.0.6~ubuntu22.04.1} date dom 10 set 2023, 11:59:58
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-10T11:59:58+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.6-7.0.6~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
%
G90
G05
T1
X4.1575Y-4.2957
X4.1575Y-4.5232
T2
X5.9016Y-4.4685
T0
M30
